### ISSUE TITLE
WIndows exe linking fail

### ISSUE THREAD

**Issue by mrsteyk** [fogleman/Craft#155]
I use standart instruction o compile, but at half it fail to link exe! Log:
[ 50%] Built target glfw
Linking C executable craft.exe
CMakeFiles\craft.dir/objects.a(auth.c.obj):auth.c:(.text+0xae): undefined reference to `_imp__curl_easy_init'
CMakeFiles\craft.dir/objects.a(auth.c.obj):auth.c:(.text+0x119): undefined reference to `_imp__curl_easy_setopt'
CMakeFiles\craft.dir/objects.a(auth.c.obj):auth.c:(.text+0x188): undefined refer
ence to `_imp__curl_easy_perform'
CMakeFiles\craft.dir/objects.a(auth.c.obj):auth.c:(.text+0x1a3): undefined reference to `_imp__curl_easy_getinfo'
CMakeFiles\craft.dir/objects.a(auth.c.obj):auth.c:(.text+0x1ac): undefined reference to `_imp__curl_easy_cleanup'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: CMakeFiles
\craft.dir/objects.a(auth.c.obj): bad reloc address 0x20 in section `.eh_frame'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: final link
 failed: Invalid operation
collect2.exe: error: ld returned 1 exit status
CMakeFiles\craft.dir\build.make:504: recipe for target 'craft.exe' failed
mingw32-make[2]: *** [craft.exe] Error 1
CMakeFiles\Makefile2:59: recipe for target 'CMakeFiles/craft.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/craft.dir/all] Error 2
Makefile:115: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by mrsteyk** [comment]
FIXED! I need to let cmake to find curl by his own way!

**Comment by sharabiania** [comment]
How exactly did you fix it?
