### ISSUE TITLE
Why don't you have comments??

### ISSUE THREAD

**Issue by PrestonLaw** [fogleman/Craft#160]
I didn't bother totaling the number of comment lines up, but it's ridiculously small, and most files have no comments at all.  I had wanted to show my sister this so she can see how OpenGL works, but there's no way she's going to be able to understand this program's workings without any comments for the important parts.

I don't care how clear you think your code is, this is terrible and you should feel bad.

**Comment by derhuerst** [comment]
@PrestonLaw

> I had wanted to show my sister this so she can see how OpenGL works, but there's no way she's going to be able to understand this program's workings without any comments for the important parts.

This may be right.

> I don't care how clear you think your code is, this is terrible and you should feel bad.

I guess this is the wrong attitude when you deal with small community-driven projects. If you think this is unacceptable, help and improve this project by adding documentation. This way, your sister and other people around the planet can contribute, based on the knowledge the derive from the comments you added. (;

**Comment by Aaron1011** [comment]
@PrestonLaw: The most charitable assumption I could make about your is that it's a complete joke. Sadly, this doesn't seem to be the case.

You have a very, welll, *interesting* idea of how open source works. Specifically, you seem to feel entitled to have the project be exactly the way you want it - and you get mad when it's not already that way. I cannot possibly emphasize this enough - **this is not how open source works**.

**Comment by derhuerst** [comment]
@PrestonLaw If you want to contribute, consider doing this at [konstructs/client](https://github.com/konstructs/client), since [it is a fork being actively developed](https://github.com/fogleman/Craft/issues/112#issuecomment-122273638).

**Comment by fogleman** [comment]
Manage your expectations. You aren't going to go from complete beginner to OpenGL expert by briefly looking at my code.
