### ISSUE TITLE
Server Doesn't Work

### ISSUE THREAD

**Issue by ThePixelPony** [fogleman/Craft#162]
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from world import World
  File "/Users/Pixel/Desktop/Craft-1.0/world.py", line 7, in <module>
    dll = CDLL('./world')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(./world, 6): image not found

I am on OS X with Python 2.7.7.

**Comment by ThePixelPony** [comment]
It does work with Python 3 either;

  File "server.py", line 59
    print line
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by wenLiangcan** [comment]
You should build the `world` file first and then run `server.py` with Python 2, this is described by [`README`](https://github.com/fogleman/Craft#server)

```
gcc -std=c99 -O3 -fPIC -shared -o world -I src -I deps/noise deps/noise/noise.c src/world.c
```

**Comment by ThePixelPony** [comment]
Ahh, thanks. That worked.

However, a different error is now displayed.

>Traceback (most recent call last):
>  File "server.py", line 8, in <module>
>    import requests
>ImportError: No module named requests

This is executed from the root directory of the project.

**Comment by wenLiangcan** [comment]
The script requires the Python module `requests`. You can do a search for how to install Python module on your system.

**Comment by ThePixelPony** [comment]
Oh, I see! Well, this is working perfectly now. I love the project. Thanks very much!
