### ISSUE TITLE
Unsure how to add accounts to a local server

### ISSUE THREAD

**Issue by rustyrp** [fogleman/Craft#165]
I've read through everything I can find, including forks and many of the issue threads here, and I can't see how (short of reading *and* *digesting* the server source) to simply create users on a local server.

I see there is a hard-coded reference to hitting the michaelfogleman.com servers, but this is for a small offline local network.  Think kids.  Think no internet access, but still a desire to play games.  The "Visit ... to register" just serves to frustrate (sorry).

It might be tolerable to play as "guest1" and "guest2" all the time, except for the fact that you can't do any world editing without being logged in!  I suppose this would be the easiest thing to look for in the code to modify, but it doesn't feel like the *right* thing to do.

The closest thing I found was mention of a "CraftBirds" at (https://github.com/fogleman/Craft/issues/151), that said "It's just a python script that adds users to a Craft server.", but there's absolutely no documentation and the pictures don't lead one to believe it just adds users.

Other than this, it seems perfect for a very lightweight type construction game.  Am I completely misunderstanding the open nature of this project?  It seems tied into your site/server.

**Comment by fogleman** [comment]
I made some changes to server.py to make authentication optional.

If you set `AUTH_REQUIRED = False` anyone can make changes and they can set their nick with `/nick nickname`.

https://github.com/fogleman/Craft/commit/3179fd3b26b5d318cae7d82343322d608a5b1d3b

_So sorry that my open source side project did not immediately solve your use case._

**Comment by rustyrp** [comment]
Argh, I read my comment again and see how you could have taken it more harshly than intended -- it was written in the middle of the night after having pored over not just your project but a few others.  I've often wondered how people can b*tch the way they do about stuff people make and share for free, but I guess that's the world open-source sharers like yourself live in.  So it pains me to hear that it sounds like you read my comment differently than intended.  You're probably sensitized to it by now, and I'm sure I would have been more thoughtful if I was wide awake.

I still don't understand why there's a hard-coded connection to a 3rd party (your) server in a project like this, but my intent isn't to gripe, just to understand.  If a client is intended to use your server, then it seems like we wouldn't need our own server.  But if we're running a local server, then I just don't understand the purpose of authenticating -- or communicating at all -- with another server.  If you're up for explaining what you had in mind, that's great.  If not, I'm certainly not going to gripe about it.

All this aside, an amazing response on your part.  Seriously, 6 hours to get a patch that sounds like it may very well work for us, that's awesome.  I'll give it a try tonight and even though you closed the issue I'll follow up here and let you know how it goes.  Thanks.

**Comment by fogleman** [comment]
The idea was that people could run their own game servers (have their own shared world) but continue to use my login server instead of having to run their own.

Obviously hard coding it isn't the best, but changing that was never a priority.

I should note that with this latest change, the auth server can still be used even when `AUTH_REQUIRED = False`, it's just not required to make changes in the world or to set your nick on the fly. So another potential change would be to allow disabling it completely.
