### ISSUE TITLE
Build failing M_PI

### ISSUE THREAD

**Issue by seemsindie** [fogleman/Craft#167]
Hello, i am getting this error when running make:

```
/home/ivan/Projects/Private/Craft/deps/glfw/examples/boing.c: In function ‘deg2rad’:
/home/ivan/Projects/Private/Craft/deps/glfw/examples/boing.c:129:28: error: ‘M_PI’ undeclared (first use in this function)
    return deg / 360 * (2 * M_PI);
                            ^

```
I am using arch linux, i have cmake, make, glfw, tried to install other deps...
Any idea why is failing?

**Comment by telpalbrox** [comment]
Same here, using Ubuntu 14.04 with all dependencies installed.

**Comment by etamme** [comment]
same here again - ubuntu 14.04

**Comment by fogleman** [comment]
Why don't one of you put this in an appropriate place and submit a pull request?

    #ifndef M_PI
    #define M_PI 3.14159265358979323846
    #endif

**Comment by etamme** [comment]
it looks like its a c99 thing, i think adding gcc -lm will fix it .. testing it now

**Comment by etamme** [comment]
yeah POSIX doesnt include M_PI, we need a #define _GNU_SOURCE added to the files that need M_PI.  I'll see if i can get a PR together

**Comment by fogleman** [comment]
I see this in the GLFW files that use M_PI, probably an appropriate place to add another...

    #if defined(_MSC_VER)
     // Make MS math.h define M_PI
     #define _USE_MATH_DEFINES
    #endif

**Comment by etamme** [comment]
yeah im bsically changing that to 

'''
#if defined(_MSC_VER)                                                           
 // Make MS math.h define M_PI                                                  
 #define _USE_MATH_DEFINES                                                      
#elif __GNUC__                                                                  
 #define _GNU_SOURCE                                                            
#endif    
'''
