### ISSUE TITLE
can't build on Mint

### ISSUE THREAD

**Issue by polycopter** [fogleman/Craft#174]
I will be happy to post error messages here if anyone is reading this list. the 1st indication something's wrong is when I type "sudo apt-get build-dep glfw" and I get an error to the effect "there's nothing in your sources.list"

**Comment by Krakn** [comment]
See: https://stackoverflow.com/questions/25151085/unable-to-locate-package-glfw-on-linux-mint

**Comment by polycopter** [comment]
I just got it to build & run (using Mint); unfortunately I don't know what I did -- it was a side-effect of some other activity, I think. I will close this issue.
