### ISSUE TITLE
Seed based terrain ?

### ISSUE THREAD

**Issue by sourceprocoder** [fogleman/Craft#206]
I appreciate the work you did. Getting good FPS and no lags at all.
But what about seed based world generation ?

```c
srand(seed);
rand(); // Numbers around seed.
```

**Comment by twetzel59** [comment]
The terrain is generated using the noise functions, not just ``rand()``. Luckily, the noise lib has a function called ``seed()``. If you call it somewhere in ``main()`` before terrain is generated, you should be able to get new terrain.

**Comment by sourceprocoder** [comment]
Thanks. I was a noob back then and don't know about noise functions.
