### ISSUE TITLE
Performance expectations

### ISSUE THREAD

**Issue by rschwiebert** [fogleman/Craft#223]
Hi: I've read in several places about how Craft is "blazing fast" and yet on my computer it is significantly choppy in horizontal directions.  Things seem fast when you are looking downwards and upwards, so I guess that makes sense if things get slower looking through the plane on the ground.

Of course, the problem could be the computer. I'd like to ask if the slow behavior should be par for the outdated system I'm about to describe, or if I could be configuring things or making adjustments that could permit normal performance.

Windows 7 (x64)
Processor: Intel Core i32120, 3.30 GHz, 2 cores
RAM: 6 GB
Intel HD Graphics (1696 MB)
DirectDraw, Direct3D, AGP texture acceleration all enabled

Thanks in advance

**Comment by fogleman** [comment]
Sounds like your video card just can't handle the number of triangles. (When looking up or down more chunks will get culled by the CPU.)

You can try typing `/view 6` or some other value while playing to reduce the viewing distance.

**Comment by rschwiebert** [comment]
@fogleman Great! I was hoping for something like that.  What range of inputs does `/view` accept, and what is it likely at now?

**Comment by rschwiebert** [comment]
`/view 4` does the trick for our purposes... thanks!
