### ISSUE TITLE
Is the account api backend public?

### ISSUE THREAD

**Issue by ChillerDragon** [fogleman/Craft#263]
First of all cool project. And I know its a side project and there is not a lot of uptime to expected but I decided to still ask.

I was not able to reach https://craft.michaelfogleman.com/ using my browser nor to connect via
```
$ ./craft michaelfogleman.com
connect: Connection refused
$ ./craft craft.michaelfogleman.com
connect: Connection refused
```

And running ``python server.py`` worked fine and I was able to play there but it feels like it is not fully replacing https://craft.michaelfogleman.com/api/1/ is there a way to host a server where users can register accounts in the case of craft.michaelfogleman.com being down?

**Comment by fogleman** [comment]
Hi. Yes, I recently took down craft.michaelfogleman.com after many years.

You can try running your own login server:

https://github.com/fogleman/LoginServer

**Comment by ChillerDragon** [comment]
Awesome! Maybe that repository could be mentioned in the readme?

**Comment by ChillerDragon** [comment]
It would be nice if you could start your server again but if you do not want to it would probably better to replace the url  https://craft.michaelfogleman.com in the readme with https://github.com/fogleman/LoginServer and then this issue can be closed I guess.
