### ISSUE TITLE
well it seems there is a ad ware trojan in the files

### ISSUE THREAD

**Issue by clerickx** [fogleman/Craft#271]
https://www.virustotal.com/gui/file/9c9a45e548795ba96586adb6121d22c6ffe17a41f2cfcfdd6ac181e280e504dd/detection
https://www.virustotal.com/gui/file/aa1e5aec387f0cffe58c3491c683600d93f0403e8cb1109847bec759394a1e99/detection

these results here are from craft.zip file from your website and the second link is for craft.exe in the folder sooooooooooooooo is it safe to run this thing plz confirm it

**Comment by KcTec90** [comment]
yes it is safe it's a false positive my anti virus (McAffe) didnt say anything...

**Comment by clerickx** [comment]
but virus total did tell me everything

**Comment by KcTec90** [comment]
https://www.virustotal.com/gui/url/a9a94c66b09cb7b44f65e6fb9f4568b4aaccadd1bf4ad4da8c16fc7e6c10f00c/detection

**Comment by MistUnky** [comment]
those 2 anti-viruses are well known for a high false positive rate.

**Comment by YusufSuleman** [comment]
@MistUnky gives a clear conclusion. So we should close this.

**Comment by Techconix** [comment]
> @MistUnky gives a clear conclusion. So we should close this.

yes
